### ISSUE TITLE
format method yields empty string when given Date milliseconds is less than 100

### ISSUE THREAD

**Issue by waltsully** [eakoriakin/date-time-js#2]
![code](https://user-images.githubusercontent.com/33215029/37208502-95d5dd9e-236f-11e8-8cfa-87a56b78aa87.PNG)

![output](https://user-images.githubusercontent.com/33215029/37208513-9d814c72-236f-11e8-8408-91c08a3203b9.PNG)

**Comment by eakoriakin** [comment]
Hi Walter, I think it expects 3 digits for milliseconds, e.g. 005 or 089. But, 5 and 89 should also be valid formats.

I can’t check the code right now as I’m traveling, but I’ll have a look on Sunday.

**Comment by waltsully** [comment]
@eakoriakin/date-time-js<mailto:date-time-js@noreply.github.com>

Thank you for the “instant” status update!  I love the rich functionality!
I posted my code so you could see my use case. Btw, when mS >100 all life is beautiful. See below.

I’ll share with you I wanted your Date function for the arithmetic …to easily render local time to my users. Thanks for your contribution of the library.

[cid:image001.png@01D3B783.64AB40E0]


[cid:image002.png@01D3B783.64AB40E0]

**Comment by waltsully** [comment]
![code2](https://user-images.githubusercontent.com/33215029/37210658-8888f3c6-2377-11e8-8b2a-66c72193c761.PNG)
![output2](https://user-images.githubusercontent.com/33215029/37210659-889ac006-2377-11e8-8eca-027c1c69411c.PNG)

**Comment by eakoriakin** [comment]
I added support for 1 and 2 digit millisecond in 1.0.6 version.
Try to update and see if it works for you.

Also, please star the project if you find it helpful 🙂

**Comment by waltsully** [comment]
Thank you! Version 1.0.6 works perfectly! All use cases...
![date time js use case code](https://user-images.githubusercontent.com/33215029/37284484-149dba0c-25d2-11e8-8c91-30ce82dfb72e.PNG)
![date time js use case tested](https://user-images.githubusercontent.com/33215029/37284485-14ad868a-25d2-11e8-97ed-17b044d46e3e.PNG)
